name: Deploy .NET API to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Docker to allow insecure registries
      run: |
        echo '{"insecure-registries":["20.244.90.237:5000"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Build and push Docker image
      run: |
        sudo docker build -t myapi BusinessCard
        sudo docker tag myapi 20.244.90.237:5000/myapi:latest
        sudo docker push 20.244.90.237:5000/myapi:latest

    - name: Deploy to Docker
      uses: appleboy/ssh-action@master
      with:
        host: 20.244.90.237
        username: carrierUser
        password: m+EsPj8YqhW^tUzw#3e"NC
        script: |
          # Stop the old container if it exists
          sudo docker ps -q --filter "name=myapi" | xargs -r sudo docker stop
          # Remove the old container if it exists
          sudo docker ps -a -q --filter "name=myapi" | xargs -r sudo docker rm
          # Pull the latest image
          sudo docker pull 20.244.90.237:5000/myapi:latest
          # Run the new container on port 5001
          sudo docker run -d -p 5001:5001 --name myapi 20.244.90.237:5000/myapi:latest

